language: node_js

node_js:
  - "10"

addons:
  ssh_known_hosts: heapy.io

before_script:
  - yarn install

script:
  - yarn run build

deploy:
  - provider: script
    script: bash .ci/deploy.sh
    skip_cleanup: true
    on:
      branch: master

cache:
  yarn: true
